[package]
name = "geode"
version = "2.4.4"
authors = ["HJfod <dreadrollmusic@gmail.com>", "Camila314 <ilaca314@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
colored = "2"
dirs = "4.0.0"
fontdue = "0.7.2"
git2 = "0.17.1"
glob = "0.3.0"
image = "0.24.3"
imageproc = "0.23.0"
signed-distance-field = "0.6.3"
path-absolutize = "3.0.11"
plist = "1.3.1"
rustyline = "9.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha256 = "1.0.3"
texture_packer = "0.24.0"
walkdir = "2"
zip = "0.5.13"
semver = "1.0.14"
reqwest = { version = "0.11.12", features = ["json", "blocking"] }
cfg-if = "1.0.0"
regex = "1.6.0"
sha3 = "0.10.6"
hex = "0.4.3"
edit-distance = "2.1.0"
which = "4.3.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.7.0"
ansi_term = "0.12"

[build-dependencies]
winres = "0.1.12"
